---

- name: install MariaDB Packages
  package: name="{{ item }}"
           state=present
  with_items:
    - mariadb-server
    - MySQL-python

- name: start MariaDB service
  service: name=mariadb
           state=started
           enabled=yes        

- name: Remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent